apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ace-app
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: cicd
  source:
    repoURL: "http://10.6.14.73/root/cicd.git"
    targetRevision: master
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false