apiVersion: v1
kind: Secret
metadata:
  name: build-repo
  namespace: openshift-gitops
spec:
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://10.6.14.73/root/cicd.git
  password: YOUR_USER
  username: YOUR_PASSWD